main1: main1.c generacion.c generacion.h
	gcc -o main1 main1.c generacion.c generacion.h
main2: main2.c generacion.c generacion.h
	gcc -o main2 main2.c generacion.c generacion.h
main3: main3.c generacion.c generacion.h
	gcc -o main3 main3.c generacion.c generacion.h
main4: main4.c generacion.c generacion.h
	gcc -o main4 main4.c generacion.c generacion.h
main5: main5.c generacion.c generacion.h
	gcc -o main5 main5.c generacion.c generacion.h
clean:
	rm -f main1 ej1 ej1.o ej1.asm
	rm -f main2 ej2 ej2.o ej2.asm
	rm -f main3 ej3 ej3.o ej3.asm
	rm -f main4 ej4 ej4.o ej4.asm
	rm -f main5 ej5 ej5.o ej5.asm
