CalcC: CalcC.c
	gcc -o CalcC CalcC.c
CalcArgs: CalcArgs.c
	gcc -o CalcArgs CalcArgs.c
clean:
	rm -f CalcC CalcArgs CalcNASM CalcNASM.o CalcCAutogenerado
	rm -f CalcCAutogenerado.asm CalcCAutogenerado.o
